// Content for the Sojourn journal essays — one generated page each.
//
// `body` is a list of blocks: {p}, {h2}, {quote} or {ul:[...]}.
// Images are ids already visually verified against their captions; if you add
// one, look at it first (see the note at the top of destinations.data.js).

module.exports = {
  site: 'https://sojourn-house.netlify.app',
  articles: [
    {
      slug: 'shoulder-season-is-the-new-peak',
      cat: 'Slow Travel',
      title: 'Shoulder season is the new peak',
      metaTitle: 'Shoulder Season Is the New Peak — Sojourn Journal',
      metaDesc: 'The discerning are quietly abandoning July. A case for the softer light, open tables and halved crowds of the in-between months — and how to plan around them.',
      excerpt: 'Why the discerning are trading July crowds for the softer light and open tables of the in-between months.',
      author: 'Camille Ardent',
      date: '2026-07-18',
      dateLabel: '18 July 2026',
      read: '6 min read',
      img: { id: 'photo-1470071459604-3b5ec3a7fe05', alt: 'Mist drifting through a forested valley in the soft light of the off-season.' },
      tags: ['Slow Travel', 'Planning', 'Seasonality'],
      body: [
        { p: 'There is a particular kind of traveler who has stopped asking when a place is at its best and started asking when it is at its quietest. For them, the calendar has inverted. The weeks everyone else calls peak — the crowded, sun-blanched heart of summer — have become the season to avoid. The margins, the shoulders, the almost-seasons on either side: that is where the good travelling now happens.' },
        { p: 'It is easy to mistake this for thrift. It is not. Shoulder-season travel can cost as much as any other; what it buys is different. Not a discount, but a dividend — of light, of space, of the sense that a place is being itself rather than performing for a crowd.' },
        { h2: 'What the crowds take with them' },
        { p: 'Visit the Amalfi Coast in early June or late September and you meet a different coast entirely. The same cliffs, the same lemon terraces, but the roads move, the restaurants have tables, and the light — lower, softer, kinder to both the landscape and the photographs — arrives without the flattening glare of August noon.' },
        { quote: 'The luxury is not that it is cheaper. The luxury is that it is emptier.' },
        { p: 'The staff are different too. In the off-months they have time; the concierge who is triaging four hundred guests in July can, in October, actually plan your day. Service, that most quoted of luxuries, is largely a function of ratio. Improve the ratio and you improve everything downstream of it.' },
        { h2: 'The strategy, in practice' },
        { p: 'Planning for shoulder season is less about the destination than the timing, and timing rewards a little discipline. A few principles we return to again and again:' },
        { ul: [
          '<strong>Chase the fortnight, not the month.</strong> Every destination has a narrow window where weather still holds but crowds have gone. It is often only two weeks wide. Find it, and build around it.',
          '<strong>Read the weather like a local, not a brochure.</strong> "Rainy season" rarely means all-day rain; it often means a spectacular afternoon hour and then clear, washed light. The brochures never tell you this.',
          '<strong>Let the calendar flex.</strong> The best shoulder trips move by a week when the forecast asks them to. Book the kind of stays that let you.',
        ] },
        { h2: "Where we're sending people this year" },
        { p: 'Kyoto in late November, once the tour buses thin and the maples turn. The Cyclades in the first fortnight of October, the sea still warm, the ferries half empty. The Alps in the green shoulder of early summer, before the season proper, when the valleys are yours and the spas are unhurried.' },
        { p: "None of these are secrets, exactly. They are simply the same beloved places, met a few degrees off the crowd's timing — which turns out to make all the difference. Peak was never the best time to go. It was only the most obvious." },
      ],
    },

    {
      slug: 'the-quiet-case-for-conscious-luxury',
      cat: 'Conscious Luxury',
      title: 'The quiet case for conscious luxury',
      metaTitle: 'The Quiet Case for Conscious Luxury — Sojourn Journal',
      metaDesc: 'Sustainability has quietly become the ultimate status symbol in travel. What it actually asks of the traveler, beyond the towel card.',
      excerpt: 'Sustainability has quietly become the ultimate status symbol. What it actually asks of the traveler.',
      author: 'Noor Haddad',
      date: '2026-06-30',
      dateLabel: '30 June 2026',
      read: '8 min read',
      img: { id: 'photo-1441974231531-c6227db76b6e', alt: 'Sunlight falling through an old forest.' },
      tags: ['Conscious Luxury', 'Sustainability', 'Ethics'],
      body: [
        { p: 'The card on the bathroom shelf asking you to reuse your towel is, by now, a punchline. It saves the property money and asks nothing of it. Everyone understands this, and nobody says so, and the card stays on the shelf.' },
        { p: 'Meanwhile, something more interesting has happened at the top of the market. Conscious travel has stopped being a discount on comfort and started being a marker of taste — the quiet signal that you know how a place actually works. It is no longer about giving things up. It is about knowing what your presence costs and choosing to pay it properly.' },
        { h2: 'The three questions worth asking' },
        { p: 'Most sustainability claims collapse under three plain questions, and almost none of them appear in a brochure.' },
        { ul: [
          '<strong>Who owns it?</strong> A lodge owned by the valley it sits in behaves differently to one owned four time zones away. Ownership determines where the money sleeps.',
          '<strong>Who works there, and in which jobs?</strong> Local employment is easy to claim and easy to check. Look at who is running the kitchen and who is running the property.',
          '<strong>What happens in the low season?</strong> The honest answer separates a business from a seasonal extraction. Places that keep paying through the quiet months are places with roots.',
        ] },
        { quote: 'The question is not whether a place is sustainable. It is who benefits when you are asleep.' },
        { h2: 'Fewer, longer, deeper' },
        { p: 'The single largest lever is also the least discussed: go less often and stay longer. A ten-night stay is not merely more restful than two five-night ones — it is a fraction of the flying, a fraction of the churn, and considerably more money left in one place rather than scattered across three.' },
        { p: 'This is also, conveniently, the better trip. The first three days of anywhere are spent orienting. Leave on day five and you have paid for the orientation and skipped the reward. Stay through the second week and a place begins to open — the market stallholder recognises you, the itinerary dissolves, and something closer to living replaces something closer to sightseeing.' },
        { h2: 'What we will and will not book' },
        { p: 'We are not purists and we do not lecture. But there are things we decline: properties built on displaced communities, wildlife experiences that involve contact with sedated animals, and anywhere the water bill of the guests exceeds the water available to the village. These are not difficult calls, and it is faintly embarrassing how often they still need making.' },
        { p: 'What is left, once you apply even a modest filter, is not a diminished list. It is a better one. The most careful properties tend also to be the most interesting, for the same reason careful people usually are: they have thought about what they are doing.' },
      ],
    },

    {
      slug: 'rooms-that-ask-nothing-of-you',
      cat: 'Design',
      title: 'Rooms that ask nothing of you',
      metaTitle: 'Rooms That Ask Nothing of You — Sojourn Journal',
      metaDesc: 'On the rise of the un-designed suite — and why true luxury in a hotel room increasingly means restraint rather than statement.',
      excerpt: 'On the rise of the un-designed suite — and why true luxury increasingly means restraint.',
      author: 'Idris Vale',
      date: '2026-06-12',
      dateLabel: '12 June 2026',
      read: '5 min read',
      img: { id: 'photo-1512918728675-ed5a9ecdebfd', alt: 'A restrained, light-filled bedroom in warm daylight.' },
      tags: ['Design', 'Hotels', 'Restraint'],
      body: [
        { p: 'There was a decade — we all lived through it — when hotel rooms shouted. Feature walls. Statement bathtubs placed, inexplicably, at the foot of the bed. Lighting systems requiring a tutorial. Every surface working hard to be photographed, and the guest reduced to an extra in someone else\'s portfolio.' },
        { p: 'That decade is ending, and what is replacing it is harder to do and much easier to live in.' },
        { h2: 'The test is the second morning' },
        { p: 'A room reveals itself not on arrival but on the second morning, when the novelty has gone and you simply need to find your things, make a coffee and sit somewhere comfortable to read. Rooms designed for the arrival photograph rarely survive this. Rooms designed for the second morning almost always do.' },
        { quote: 'A good room does not introduce itself. You notice it three days later, by the absence of irritation.' },
        { p: 'The details that matter turn out to be dull to photograph and expensive to get right: a bedside light you can dim with one hand in the dark, a wardrobe that opens without a manual, a desk at the correct height, a bathroom where the mirror does not fog, sockets on both sides of the bed, and a door that closes with a sound rather than a bang.' },
        { h2: 'Restraint is not minimalism' },
        { p: 'This is worth separating, because they are often confused. Minimalism is a look — white, hard, sparse, and frequently as demanding as the maximalism it replaced. Restraint is a discipline: the room may be warm, layered, full of texture and books and worn leather, but nothing in it is asking for your attention.' },
        { p: 'The best examples we know are often the least fashionable: an old ryokan room with nothing in it but tatami, a scroll and a view; a Provençal farmhouse bedroom with lime-washed walls and a chair by the window; a fjord cabin that is essentially a well-made box aimed at the water. None of them are trying. All of them work.' },
        { h2: 'What this means when you book' },
        { p: 'Look past the hero shot. Ask for a photograph of the desk, the wardrobe, the actual light at 7pm. Ask what the room sounds like — from the corridor, from the street, from the room above. Ask whether the windows open, which sounds absurd until the third night in a sealed box.' },
        { p: 'The rooms worth returning to are rarely the ones that impressed you. They are the ones that let you stop noticing the room at all, which is, in the end, the whole point of somewhere to sleep.' },
      ],
    },

    {
      slug: 'the-overwater-spa-reconsidered',
      cat: 'Wellness',
      title: 'The overwater spa, reconsidered',
      metaTitle: 'The Overwater Spa, Reconsidered — Sojourn Journal',
      metaDesc: 'Beyond the massage menu: what a genuinely restorative week is engineered to feel like, and why most spa weeks quietly fail at it.',
      excerpt: 'Beyond the massage menu: what a genuinely restorative week is engineered to feel like.',
      author: 'Camille Ardent',
      date: '2026-05-28',
      dateLabel: '28 May 2026',
      read: '7 min read',
      img: { id: 'photo-1571003123894-1f0594d2b5d9', alt: 'Poolside cabanas at the water’s edge in the last of the light.' },
      tags: ['Wellness', 'Rest', 'Planning'],
      body: [
        { p: 'The overwater spa is one of travel\'s great images: a glass floor, a lagoon moving underneath, a treatment room suspended over turquoise. It photographs beautifully. It is also, on its own, close to useless — and the gap between the image and the outcome is where most wellness weeks quietly fail.' },
        { p: 'The failure is structural. A spa week is usually sold as a menu: pick eight treatments, distribute them across seven days, arrive home tired in a slightly different way. Nothing in that structure is designed to produce rest. It is designed to produce bookings.' },
        { h2: 'Rest is a schedule problem' },
        { p: 'Genuine restoration turns out to be less about what you do and more about what the week does to your nervous system. That means a shape, not a list. The pattern we now build looks roughly like this:' },
        { ul: [
          '<strong>Days one and two: subtract.</strong> No treatments at all. Sleep badly, then sleep well. Let the travel leave your body before you start doing anything to it.',
          '<strong>Days three to five: one thing a day.</strong> A single appointment, always in the morning, and nothing scheduled after it. The afternoon is the treatment.',
          '<strong>Days six and seven: build.</strong> Movement, water, something mildly demanding — a long swim, a walk with height in it — so you return with momentum rather than inertia.',
        ] },
        { quote: 'The massage is not the intervention. The empty afternoon after it is.' },
        { h2: 'What to ask a spa before you commit' },
        { p: 'Two questions separate the serious from the decorative. First: is there a practitioner who sees me more than once, and do they talk to each other? A week of eight strangers each performing sixty minutes is a sequence of transactions, not a programme. Second: what happens at night? Sleep is the entire mechanism, and a property that has thought about blackout, temperature, sound and a genuinely early dinner is doing more for you than any treatment room over water.' },
        { h2: 'The case for the water, after all' },
        { p: 'None of which is an argument against the lagoon. Cold water in particular has earned its reputation — a sea swim before breakfast does something no table can. And there is a real, unmeasurable benefit to a room where the floor moves with the tide and the only sound at three in the morning is water against timber.' },
        { p: 'Keep the overwater spa. Just stop treating it as the plan. The plan is the emptiness around it, and emptiness, it turns out, is the hardest thing on earth to book.' },
      ],
    },

    {
      slug: 'a-table-for-two-on-an-empty-sandbank',
      cat: 'Gastronomy',
      title: 'A table for two on an empty sandbank',
      metaTitle: 'A Table for Two on an Empty Sandbank — Sojourn Journal',
      metaDesc: 'The theatre of the private dinner — why the best meals increasingly have no other guests, and when the whole idea goes wrong.',
      excerpt: 'The theatre of the private dinner — and why the best meals now have no other guests.',
      author: 'Idris Vale',
      date: '2026-05-09',
      dateLabel: '9 May 2026',
      read: '6 min read',
      img: { id: 'photo-1467003909585-2f8a72700288', alt: 'A plated course served at a small private table.' },
      tags: ['Gastronomy', 'Private Dining', 'Design'],
      body: [
        { p: 'Somewhere in the last few years the private dinner stopped being a special occasion and became a category. Every resort now offers one: a table carried to a beach, a sandbank, a ruined tower, a boat. Lanterns are involved. There is almost always a path of petals, and it is almost always a mistake.' },
        { p: 'Which is a shame, because the underlying idea is sound. Eating well in a place nobody else is standing in is one of the genuine pleasures of travelling. It is the execution that has gone industrial.' },
        { h2: 'Why most of them fail' },
        { p: 'The failure is usually one of three kinds. The food travels badly, because a kitchen four hundred metres away cannot plate anything that needs to arrive hot. The service is too close, because two staff standing at a respectful distance in an otherwise empty landscape are not at a respectful distance at all. Or the staging overwhelms the point — you have been placed inside someone\'s idea of romance, and there is nowhere to look that is not decorated.' },
        { quote: 'The test of a private dinner is whether you could have a real conversation at it. Most are designed to be photographed, not talked at.' },
        { h2: 'What the good ones get right' },
        { ul: [
          '<strong>The kitchen comes too.</strong> A fire, a grill, a chef working ten metres away. Food that was never transported, and something to watch that is not each other.',
          '<strong>One person, not four.</strong> A single host who pours and then genuinely leaves. Staff briefed to be summoned rather than present.',
          '<strong>The place does the decorating.</strong> If the setting needs petals, the setting is not good enough. A sandbank at dusk requires a table, chairs, light and nothing else.',
          '<strong>An exit.</strong> The best of them last ninety minutes, not four hours. Knowing you can walk back when you like is most of what makes it relaxing.',
        ] },
        { h2: 'The version we book most often' },
        { p: 'Not, as it happens, the sandbank. It is usually a long table in the property\'s own kitchen garden, or on a terrace that belongs to the house rather than to the marketing department — the chef cooking what the market had, one wine, no menu, and the option to move indoors when it cools.' },
        { p: 'It costs less than the lantern-lit version and it is better in every respect that matters. The extraordinary meal, it turns out, is rarely the extraordinary production. It is usually just excellent food, somewhere quiet, with nobody hovering.' },
      ],
    },

    {
      slug: 'kyoto-before-the-crowds',
      cat: 'Culture',
      title: 'Kyoto before the crowds',
      metaTitle: 'Kyoto Before the Crowds — Sojourn Journal',
      metaDesc: 'How a private guide and a 6am start turn the world’s most photographed city into your own — and which mornings are worth the alarm.',
      excerpt: "How a private guide and a 6am start turn the world's most photographed city into your own.",
      author: 'Noor Haddad',
      date: '2026-04-22',
      dateLabel: '22 April 2026',
      read: '9 min read',
      img: { id: 'photo-1478436127897-769e1b3f0f36', alt: 'Vermilion torii gates along an empty Kyoto path.' },
      tags: ['Culture', 'Japan', 'Planning'],
      body: [
        { p: 'Kyoto has a reputation problem, and it is entirely the fault of the middle of the day. Between ten and four, the famous sites are a slow-moving queue with a temple attached, and every photograph you have ever admired of the city becomes visibly impossible.' },
        { p: 'The city has not changed. The hours have. Almost everything people love about Kyoto is still there, and most of it is available before eight in the morning to anyone willing to set an alarm.' },
        { h2: 'The ninety-minute advantage' },
        { p: 'Fushimi Inari is the clearest example. By eleven the lower gates are a shuffling column. At six they are silent, the light comes through the vermilion in bars, and you can walk twenty minutes up the mountain without meeting anyone. The site did not improve; you simply arrived before the coaches.' },
        { quote: 'The difference between Kyoto as a queue and Kyoto as a revelation is about ninety minutes of sleep.' },
        { p: 'The same is true of the moss gardens, of Kiyomizu\'s approach, of the bamboo at Arashiyama — which is genuinely magnificent at dawn and genuinely miserable at noon. Build the week around early mornings and unstructured afternoons and the city rearranges itself around you.' },
        { h2: 'What a guide is actually for' },
        { p: 'Not narration. You can read. A good Kyoto guide is a set of relationships: the sub-temple that will open a hall for four people, the tea practitioner who does not take visitors, the indigo dyer in the fifth generation, the counter with eight seats that has never had a listing. These cannot be booked. They can only be introduced.' },
        { p: 'Our fixer there has spent fifteen years on this, and the difference it makes is not access to more things — it is access to fewer things, properly. An hour with a knife-maker who explains why the steel is folded is worth a day of temple exteriors.' },
        { h2: 'When to go, and when not to' },
        { ul: [
          '<strong>Late November</strong> for the maples, but the last week rather than the first — the crowds follow the forecast by a few days.',
          '<strong>Early March</strong>, before the blossom, when the city is cold, clear and almost empty. Our quiet favourite.',
          '<strong>Avoid the first fortnight of April</strong> unless cherry blossom is the entire point, and even then, plan every morning for six o\'clock.',
          '<strong>Avoid Golden Week</strong> altogether. Domestic travel fills everything, and no amount of introduction fixes it.',
        ] },
        { h2: 'The afternoon rule' },
        { p: 'Having earned the mornings, do nothing with the afternoons. Kyoto punishes ambition — the city is spread out, the transit is slow, and three sites in a day means three queues and a taxi argument. One thing before breakfast, lunch somewhere small, and then a bath, a book and a walk in whichever direction looks quiet.' },
        { p: 'It is not an efficient way to see a city. It is an extremely good way to know one.' },
      ],
    },

    {
      slug: 'the-art-of-the-slow-itinerary',
      cat: 'Slow Travel',
      title: 'The art of the slow itinerary',
      metaTitle: 'The Art of the Slow Itinerary — Sojourn Journal',
      metaDesc: 'Why we now plan half as much per day — and how the empty hours became the part of the trip people actually remember.',
      excerpt: 'Why we now plan half as much per day — and how the empty hours became the point.',
      author: 'Camille Ardent',
      date: '2026-04-03',
      dateLabel: '3 April 2026',
      read: '5 min read',
      img: { id: 'photo-1500530855697-b586d89ba3ee', alt: 'An open road winding between red rock hills.' },
      tags: ['Slow Travel', 'Planning', 'Rest'],
      body: [
        { p: 'Ask someone about a trip six months later and watch what they actually remember. Almost never the itinerary. Almost always an afternoon that was not on it — a wrong turn, a long lunch that ran into evening, an hour on a wall watching a harbour do nothing in particular.' },
        { p: 'We have been planning against this for years without noticing. The proposal that looks generous — six things a day, nothing missed — is the one that guarantees none of those afternoons can happen. A full itinerary is not a rich trip. It is a trip with no room in it.' },
        { h2: 'The half rule' },
        { p: 'The change we made is embarrassingly simple: one fixed thing per day, in the morning, and nothing else committed. Not fewer good experiences — the same ones, with space around them. A morning at a vineyard becomes a morning at a vineyard and whatever the vineyard suggests over lunch, which is usually better than anything we would have booked.' },
        { quote: 'Nobody has ever come home and said the problem was that they saw too little.' },
        { h2: 'What the empty hours are for' },
        { ul: [
          '<strong>Repetition.</strong> Going back to the same café three mornings running is how a place stops being scenery. It cannot happen on a full schedule.',
          '<strong>Weather.</strong> An unplanned afternoon absorbs rain without ruining anything. A planned one turns rain into a loss.',
          '<strong>The local suggestion.</strong> The best recommendations arrive at eleven in the morning from someone you have just met, and are useless if two o\'clock is spoken for.',
          '<strong>Actual rest.</strong> Which is, for most people, the stated reason for the trip and the first thing the itinerary removes.',
        ] },
        { h2: 'How to hold the line' },
        { p: 'The pressure to fill a day is real, and it usually comes from the traveler rather than the planner — a day with nothing in it looks, on paper, like money wasted. It is worth resisting for three days, which is roughly how long it takes for the discomfort to convert into relief.' },
        { p: 'It helps to move less. Two bases in ten nights rather than four. Every transfer costs half a day at each end and buys a fresh set of orientation problems. It also helps to book stays you would happily spend an afternoon inside, because on a slow itinerary you will.' },
        { p: 'The result reads thin in a document and lands rich in memory. That trade — a less impressive plan for a better week — has become the single most useful thing we do.' },
      ],
    },

    {
      slug: 'two-bases-ten-nights',
      cat: 'Slow Travel',
      title: 'Two bases, ten nights',
      metaTitle: 'Two Bases, Ten Nights — Sojourn Journal',
      metaDesc: 'The arithmetic of moving less: why every transfer costs you a day at each end, and how a two-base trip beats a four-base one.',
      excerpt: 'The arithmetic of moving less — and why every transfer costs a day at each end.',
      author: 'Idris Vale',
      date: '2026-08-08',
      dateLabel: '8 August 2026',
      read: '5 min read',
      img: { id: 'photo-1469854523086-cc02fe5d8800', alt: 'A van on an open road between red rock formations.' },
      tags: ['Slow Travel', 'Planning', 'Logistics'],
      body: [
        { p: 'Here is a piece of arithmetic almost nobody does before booking. A transfer between two places costs roughly half a day at the departure end — the packing, the check-out, the dead hours — and half a day at the arrival end, spent finding the light switches and working out where breakfast is. Call it one day per move.' },
        { p: 'A ten-night trip with four bases therefore spends three of its ten days in transition. Nearly a third of the holiday is logistics, and it is the tiring third.' },
        { h2: 'What the second base is for' },
        { p: 'This is not an argument for staying still. Two bases is usually better than one, because the contrast is where the interest lives: the coast and then the hills, the city and then the country, the noise and then the silence. What two gives you that four does not is time to settle at each end.' },
        { quote: 'Every additional base is a day of your holiday spent being a new arrival.' },
        { p: 'The pattern we book most often on ten nights is five and five, or six and four with the longer stay second. Ending slower than you started is worth more than it sounds; it is the difference between coming home rested and coming home needing a holiday.' },
        { h2: 'When to break the rule' },
        { ul: [
          '<strong>When the transfer is the point.</strong> A crewed boat that moves overnight, or a train with a view, costs nothing in dead hours because the moving is the experience.',
          '<strong>When the second place is under an hour away.</strong> Short hops do not carry the same tax. Two villages twenty minutes apart are effectively one base.',
          '<strong>On trips over three weeks.</strong> Past a certain length, staying put starts to cost more in restlessness than moving costs in fatigue.',
        ] },
        { h2: 'The practical version' },
        { p: 'Book the transfer day as though it were a rest day, because it is one. Nothing scheduled, a late check-out at one end and an early check-in at the other, both of which are usually available and rarely asked for. Then let the arrival evening be nothing but dinner somewhere near the front door.' },
        { p: 'It reads like a smaller trip. It is a substantially larger one.' },
      ],
    },

    {
      slug: 'the-flight-you-didnt-take',
      cat: 'Conscious Luxury',
      title: "The flight you didn't take",
      metaTitle: "The Flight You Didn't Take — Sojourn Journal",
      metaDesc: 'The single biggest lever in conscious travel is the trip you consolidate rather than the offset you buy. An honest look at the numbers.',
      excerpt: 'The biggest lever is the trip you consolidate — not the offset you buy afterwards.',
      author: 'Noor Haddad',
      date: '2026-07-30',
      dateLabel: '30 July 2026',
      read: '7 min read',
      img: { id: 'photo-1518495973542-4542c06a5843', alt: 'Sunlight through the branches of a great old tree.' },
      tags: ['Conscious Luxury', 'Sustainability', 'Planning'],
      body: [
        { p: 'Offsetting is the comfortable conversation. It happens after the decision, costs a rounding error, and leaves the itinerary untouched. This is precisely why it is popular, and precisely why it does so little.' },
        { p: 'The uncomfortable conversation happens before booking, and it has one question in it: does this need to be two trips?' },
        { h2: 'The arithmetic nobody likes' },
        { p: 'Four long-haul returns a year is a different order of magnitude from two, and no amount of careful behaviour at the destination closes that gap. The linen-reuse card, the refillable bottle, the locally sourced breakfast — all worth doing, all rounding errors against the flying.' },
        { quote: 'Nothing you do at the destination competes with the decision about how often you go.' },
        { p: 'This is not a call to stop travelling, which would be both joyless and, coming from us, absurd. It is a call to be honest about where the weight sits, and then to move the thing that actually weighs something.' },
        { h2: 'Consolidation, in practice' },
        { ul: [
          '<strong>Merge the two short trips into one long one.</strong> Two five-night escapes to the same region become one twelve-night trip with a better rhythm and half the flying.',
          '<strong>Go further, less often.</strong> If somewhere is fourteen hours away, it deserves three weeks, not six nights. The distance should buy depth.',
          '<strong>Take the train where it exists.</strong> Across Europe this is now frequently the faster door-to-door option as well as the quieter one.',
          '<strong>Fly the shortest routing, not the cheapest.</strong> Two connections to save a modest amount is a poor trade on every axis including your own morning.',
        ] },
        { h2: 'What offsets are actually good for' },
        { p: 'Having consolidated, offsetting still has a place — but treat it as a donation rather than an absolution, and choose accordingly. The credible ones are usually unglamorous, local to where you travelled, and verifiable. The rest are a receipt for a feeling.' },
        { p: 'The most conscious thing in most itineraries is not a line item. It is the second trip that never got booked, and the twelve nights that replaced both.' },
      ],
    },

    {
      slug: 'who-owns-the-view',
      cat: 'Conscious Luxury',
      title: 'Who owns the view',
      metaTitle: 'Who Owns the View — Sojourn Journal',
      metaDesc: 'Conservation lodges, community land and the awkward questions worth asking before you book a wilderness stay.',
      excerpt: 'Conservation lodges, community land, and the questions worth asking before booking.',
      author: 'Camille Ardent',
      date: '2026-07-05',
      dateLabel: '5 July 2026',
      read: '8 min read',
      img: { id: 'photo-1547471080-7cc2caa01a7e', alt: 'A lone acacia against a wide plain at sunset.' },
      tags: ['Conscious Luxury', 'Wilderness', 'Ethics'],
      body: [
        { p: 'Wilderness travel has a particular moral texture. You are paying a great deal of money to be somewhere that looks untouched, and the looking-untouched is generally the result of decisions made about people who used to be there.' },
        { p: 'This is not an argument against going. Well-run conservation travel is one of the few forms of tourism that demonstrably pays for the thing it consumes. But it does mean the brochure language — "pristine", "remote", "unspoilt" — deserves a second reading.' },
        { h2: 'Three questions, again' },
        { ul: [
          '<strong>Whose land is it, legally?</strong> Community-owned concessions leased to an operator behave very differently from land bought outright. Ask which it is; the good ones answer immediately.',
          '<strong>What share of the bed-night leaves the country?</strong> A number exists. Operators who are proud of it will tell you. Operators who are not will talk about employment instead.',
          '<strong>What happens to the land if tourism stops?</strong> This is the real test of a conservation claim. If the answer is "it reverts to agriculture", the lodge is genuinely holding the line. If the answer is vague, the conservation is decorative.',
        ] },
        { quote: 'A place that looks untouched is usually a place someone is paying to keep that way. The question is who.' },
        { h2: 'The wildlife part' },
        { p: 'The rules here are simple and widely ignored. No contact with big cats, ever. No walking with, riding, bathing or holding anything that would not permit it awake and unsedated. No orphanages that also offer selfies. Where a place offers these, it is telling you what it is, and you should believe it.' },
        { p: 'The corollary is happier: the best wildlife experiences are the least interactive. A guide who reads tracks for two hours and finds nothing has given you a better morning than a guaranteed sighting at a bait station, and you will remember it longer.' },
        { h2: 'Why this is worth the discomfort' },
        { p: 'Because the alternative is a category of travel that photographs as conservation and functions as extraction, and the two are genuinely hard to tell apart from a website. Four questions, asked politely by email before booking, separate them almost every time.' },
        { p: 'The places that answer well tend to be extraordinary. That is not a coincidence — the same seriousness shows up in the guiding, the food and the quiet.' },
      ],
    },

    {
      slug: 'cold-water-plainly',
      cat: 'Wellness',
      title: 'Cold water, plainly',
      metaTitle: 'Cold Water, Plainly — Sojourn Journal',
      metaDesc: 'Cold immersion has been oversold and undersold at the same time. What it does, what it does not, and how to build a week around it.',
      excerpt: 'Cold immersion has been both oversold and undersold. What it actually does for a week.',
      author: 'Idris Vale',
      date: '2026-06-20',
      dateLabel: '20 June 2026',
      read: '6 min read',
      img: { id: 'photo-1502786129293-79981df4e689', alt: 'A glacial lake ringed by pines under low cloud.' },
      tags: ['Wellness', 'Cold Water', 'Rest'],
      body: [
        { p: 'Few things in wellness have been claimed for as loudly or as badly as cold water. It has been sold as a cure for inflammation, depression, ageing and indecision, which has had the predictable effect of making sensible people dismiss it entirely.' },
        { p: 'That dismissal is the mistake. Strip away the claims and something plain and useful remains.' },
        { h2: 'What it reliably does' },
        { p: 'Cold immersion produces a large, fast, unambiguous shift in how you feel — a sharpening that lasts a couple of hours and is genuinely difficult to obtain any other way. Whether that is adrenaline, novelty, or simply the relief of stopping, it does not much matter. It works, it is free, and it requires no equipment beyond somewhere cold to get into.' },
        { quote: 'The value is not metabolic. It is that for ninety seconds you are entirely unable to think about anything else.' },
        { p: 'The second effect is subtler and more durable: it makes the rest of the day feel warm. A cold swim at eight makes an ordinary morning feel like an achievement, and that framing carries.' },
        { h2: 'How to build a week around it' },
        { ul: [
          '<strong>Morning, not evening.</strong> Cold late in the day is stimulating at exactly the wrong time and will cost you sleep, which is the thing you actually came for.',
          '<strong>Short.</strong> Ninety seconds to three minutes. Longer is not better and eventually becomes genuinely unsafe.',
          '<strong>Warm afterwards, slowly.</strong> A sauna, a walk, a hot drink — but not immediately, and never a hot shower straight out.',
          '<strong>Never alone in open water.</strong> The dull rule that keeps this a pleasure rather than an incident.',
        ] },
        { h2: 'Where it is best' },
        { p: 'The Nordic version is the complete one: sauna, sea, repeat, ideally with the sea below ten degrees and nobody else present. Alpine lakes in early summer are the same experience at altitude. Even a Mediterranean sea in October, which is hardly cold, does a version of it at seven in the morning.' },
        { p: 'What none of these require is a programme, a practitioner or a fee. It is the cheapest thing on the wellness menu, and after a week of it most people rate it above everything they paid for.' },
      ],
    },

    {
      slug: 'sleep-is-the-whole-programme',
      cat: 'Wellness',
      title: 'Sleep is the whole programme',
      metaTitle: 'Sleep Is the Whole Programme — Sojourn Journal',
      metaDesc: 'Every restorative week runs on sleep, and most properties quietly sabotage it. What to ask for, and what to change on the first night.',
      excerpt: 'Every restorative week runs on sleep — and most properties quietly sabotage it.',
      author: 'Noor Haddad',
      date: '2026-06-03',
      dateLabel: '3 June 2026',
      read: '7 min read',
      img: { id: 'photo-1519681393784-d120267933ba', alt: 'A clear night sky above snow-covered peaks.' },
      tags: ['Wellness', 'Sleep', 'Hotels'],
      body: [
        { p: 'Ask people what they want from a week away and most say some version of rest. Then look at what is actually booked: early flights, late dinners, a treatment schedule, and a room facing a road. The stated goal and the itinerary are barely acquainted.' },
        { p: 'Sleep is not one component of a restorative trip. It is the mechanism by which every other component works, and it is the first thing a badly chosen room destroys.' },
        { h2: 'What ruins it, in order' },
        { ul: [
          '<strong>Light.</strong> Not the curtains — the standby LEDs, the corridor gap under the door, the safe glowing green in the wardrobe. Ask for a room with real blackout and then tape over what remains.',
          '<strong>Temperature.</strong> Most rooms are set several degrees too warm and many cannot be changed. Ask before booking whether the room has its own thermostat. Surprisingly often it does not.',
          '<strong>Sound.</strong> Lifts, ice machines, the service corridor, the bar terrace below. The floor plan matters more than the room category, and no upgrade fixes a bad location.',
          '<strong>Dinner at nine.</strong> A late heavy meal costs more sleep than jet lag does, and it is entirely within your control.',
        ] },
        { quote: 'A quiet, dark, cool room on the fourth floor beats a spectacular suite above the terrace, every night of the week.' },
        { h2: 'The first-night protocol' },
        { p: 'Arriving somewhere new, do three things before unpacking: find and kill every light source in the room, set the temperature as low as it will go, and work out where the noise will come from at eleven. If any of the three cannot be solved, ask to move — on the first night this is easy and cheerful, and by the third it is awkward for everyone.' },
        { h2: 'And the flying' },
        { p: 'Jet lag is largely a light problem and only slightly a sleep problem. Get outside within an hour of local sunrise on the first two mornings and most of it resolves; sit in a dim lobby recovering and it lingers for the week. It is the least sophisticated advice in wellness and reliably the most effective.' },
        { p: 'None of this is glamorous, and no property markets on it. But a week of genuine sleep does more than any programme, and it is very nearly free.' },
      ],
    },

    {
      slug: 'the-lobby-is-the-tell',
      cat: 'Design',
      title: 'The lobby is the tell',
      metaTitle: 'The Lobby Is the Tell — Sojourn Journal',
      metaDesc: 'You can predict the whole stay from the first ninety seconds in a hotel lobby. What to look for, and what it reveals.',
      excerpt: 'You can predict the whole stay from ninety seconds in the lobby. Here is what to look at.',
      author: 'Idris Vale',
      date: '2026-05-18',
      dateLabel: '18 May 2026',
      read: '5 min read',
      img: { id: 'photo-1522798514-97ceb8c4f1c8', alt: 'A planted hotel courtyard with low chairs and tiled floor.' },
      tags: ['Design', 'Hotels', 'Service'],
      body: [
        { p: 'A hotel tells you everything about itself in the first ninety seconds, and almost none of it is in the furniture. The lobby is where the building\'s priorities become visible, because it is the one space that has to serve both the guest and the operation, and the compromise is always legible.' },
        { h2: 'Four things to look at' },
        { ul: [
          '<strong>Is anyone sitting down?</strong> A lobby with guests in it is a lobby designed for guests. A beautiful empty one is a corridor with sculpture, and it means the good spaces are elsewhere or nowhere.',
          '<strong>Where is the luggage?</strong> If arriving bags are stacked in the sightline, the operation was designed after the interior. This tends to be true of everything else as well.',
          '<strong>Can you hear the room you are in?</strong> Hard surfaces and double height look magnificent and sound like a swimming pool. Listen for whether a conversation two metres away is private.',
          '<strong>Is the light on a dimmer?</strong> Lobbies lit identically at four in the afternoon and eleven at night belong to properties that have not thought about evenings.',
        ] },
        { quote: 'A lobby is a promise about how the rest of the building will treat you. It is usually kept.' },
        { h2: 'The check-in question' },
        { p: 'A desk between you and the person greeting you is a nineteenth-century idea that survives mostly through inertia. The properties worth returning to have generally abolished it — you are walked to a chair, given something to drink, and the administrative part happens beside you rather than across a counter.' },
        { p: 'This is not a small thing. It signals a building organised around the guest\'s experience of arriving rather than the staff\'s experience of processing, and that orientation shows up again at breakfast, at turndown, and on the morning you leave.' },
        { h2: 'What it does not tell you' },
        { p: 'Cost, mostly. Some of the best-judged lobbies we know belong to modest places — a stone-floored entrance hall in a Provençal mas with four chairs and a table of local wine — and some of the worst belong to the very expensive, where the budget went into a chandelier and the acoustics were left to chance.' },
        { p: 'Spend the ninety seconds. It is the most reliable prediction available, and it costs nothing but standing still.' },
      ],
    },

    {
      slug: 'buildings-that-know-where-they-are',
      cat: 'Design',
      title: 'Buildings that know where they are',
      metaTitle: 'Buildings That Know Where They Are — Sojourn Journal',
      metaDesc: 'On hotels built from the ground they stand on — and the international style that could be anywhere, and therefore is.',
      excerpt: 'On hotels built from the ground they stand on — and the ones that could be anywhere.',
      author: 'Camille Ardent',
      date: '2026-04-30',
      dateLabel: '30 April 2026',
      read: '6 min read',
      img: { id: 'photo-1455587734955-081b22074882', alt: 'A pale modernist building with deep balconies and palms.' },
      tags: ['Design', 'Architecture', 'Place'],
      body: [
        { p: 'There is a hotel room that exists in forty countries. Beige, competent, a padded headboard, a print of something abstract, a bathroom in grey stone. It is not bad. It is simply from nowhere, and waking in it tells you nothing about where you are.' },
        { p: 'The alternative is not folklore. Nobody wants a themed room. What they want, usually without being able to name it, is a building made from the assumptions of its own place.' },
        { h2: 'What local actually means' },
        { p: 'It is rarely decorative and almost always structural. Thick walls and small windows in hot dry places, because that is how you stay cool without machinery. Deep eaves where it rains. South-facing glass and a stove where it is cold. Courtyards where the street is loud. Every one of these is a response to a specific problem, and buildings that solve local problems end up looking local without trying.' },
        { quote: 'Vernacular architecture is not a style. It is several centuries of people finding out what works here.' },
        { h2: 'The material test' },
        { ul: [
          '<strong>Where did the stone come from?</strong> A wall of local limestone and a wall of imported travertine cost similar amounts and mean entirely different things.',
          '<strong>Who made the furniture?</strong> Not the brand — the workshop. The good properties can name it, and it is usually within two hours.',
          '<strong>Does the building have a shape it could not have elsewhere?</strong> A riad only makes sense in a hot walled city. A fjord cabin only makes sense on a fjord. If the form would transplant anywhere, it came from nowhere.',
        ] },
        { h2: 'Why it changes the week' },
        { p: 'Because a building that answers its own climate also teaches you the climate. You learn why the shutters close at noon in Provence by living in a house that expects you to. You understand a Japanese room\'s relationship to its garden by sitting in one at the hour it was designed for.' },
        { p: 'That is the actual luxury on offer — not the thread count, but waking up somewhere that could only be here.' },
      ],
    },

    {
      slug: 'venice-at-seven-in-the-morning',
      cat: 'Culture',
      title: 'Venice at seven in the morning',
      metaTitle: 'Venice at Seven in the Morning — Sojourn Journal',
      metaDesc: 'The most visited city in Europe is empty for two hours every day. A case for staying the night and setting an alarm.',
      excerpt: 'The most visited city in Europe is empty for two hours a day. Stay the night and find out.',
      author: 'Noor Haddad',
      date: '2026-04-12',
      dateLabel: '12 April 2026',
      read: '7 min read',
      img: { id: 'photo-1498307833015-e7b400441eb8', alt: 'A canal of pale palazzi under a pink early sky.' },
      tags: ['Culture', 'Italy', 'Planning'],
      body: [
        { p: 'Venice is the standard example of a ruined city. It is also, for about two hours each morning, one of the quietest places in Europe — and the two facts have the same cause.' },
        { p: 'The crowd is overwhelmingly a day crowd. It arrives by coach and cruise tender from about half past nine, moves along three known routes, and is gone by six. A city of fifty thousand residents hosts a multiple of that between ten and five, and almost none of it stays the night.' },
        { h2: 'The two-hour city' },
        { p: 'Which means that if you sleep in Venice, you own it at seven. The bridges are empty. The delivery boats are working, which is the city being a city rather than an exhibit. Bars are serving coffee to people going to work. The light comes off the water onto the undersides of things and there is nobody standing in it.' },
        { quote: 'Venice is not overrun. Venice is overrun between ten and five, which is a different and much more solvable problem.' },
        { p: 'The same trick works in the evening, after about seven, with the addition that everything is open. The middle of the day is simply written off — read, sleep, eat somewhere with a courtyard, and go back out when the tide of people goes.' },
        { h2: 'Where to actually go' },
        { ul: [
          '<strong>Cannaregio and Castello</strong> for the mornings. Residential, working, and outside the three routes entirely.',
          '<strong>The islands mid-afternoon</strong>, running against the flow — Torcello when everyone else is on the Rialto.',
          '<strong>The scuole rather than the basilica.</strong> Smaller, extraordinary, and frequently near-empty even at noon.',
          '<strong>A boat at dusk.</strong> Not a gondola through the middle, but a small motorboat out into the lagoon as the light goes.',
        ] },
        { h2: 'The general principle' },
        { p: 'What is true of Venice is true of nearly every over-visited place: the crowding is temporal, not spatial, and the fix is a hotel room and an alarm rather than a different destination. Dubrovnik, Kyoto, the Cinque Terre, Santorini — all of them are two cities, and the timetable decides which one you get.' },
        { p: 'People who write these places off usually visited them for six hours in August, between ten and five, along the route. It is a genuinely accurate impression of a thing that only exists part-time.' },
      ],
    },

    {
      slug: 'ninety-minutes-in-a-museum',
      cat: 'Culture',
      title: 'Ninety minutes in a museum',
      metaTitle: 'Ninety Minutes in a Museum — Sojourn Journal',
      metaDesc: 'Against the four-hour cultural death march: why a short, narrow, well-guided visit beats seeing everything.',
      excerpt: 'Against the four-hour death march — why a short, narrow visit beats seeing everything.',
      author: 'Idris Vale',
      date: '2026-03-25',
      dateLabel: '25 March 2026',
      read: '5 min read',
      img: { id: 'photo-1518998053901-5348d3961a04', alt: 'A pale gallery hung with framed photographs.' },
      tags: ['Culture', 'Museums', 'Slow Travel'],
      body: [
        { p: 'Everyone has done the four-hour museum. You arrive full of intent, you are engaged for forty minutes, interested for another thirty, and then you walk through eleven rooms of masterpieces in a state of mild despair, looking for the café and feeling faintly guilty about it.' },
        { p: 'This is not a failure of stamina or education. It is a failure of scope. Attention for looking at things runs out somewhere around the ninety-minute mark, and no amount of willpower extends it.' },
        { h2: 'Pick five things' },
        { p: 'The method that works is almost aggressively narrow: choose five objects before arriving, walk straight to them, and give each one ten minutes. Everything else is permitted to be scenery. You will see less and remember incomparably more.' },
        { quote: 'Ten minutes with one painting is a memory. Ninety seconds each with forty is a headache.' },
        { p: 'Ten minutes in front of a single painting feels absurd for the first two and then stops feeling like anything at all; it is roughly when you start actually seeing it. Most people have never done it once, which is a strange fact about a thing we all claim to enjoy.' },
        { h2: 'What a good guide is for' },
        { p: 'Not coverage. A guide who walks you through the highlights is a more expensive audio tour. The useful ones do the opposite — they take you to four things, one of which is not famous, and tell you what to look at rather than what to know. The difference is immediate: dates and attributions evaporate by dinner, but "notice what the hands are doing" stays for years.' },
        { h2: 'The practical shape' },
        { ul: [
          '<strong>First entry or last two hours.</strong> Both are quiet. Mid-morning is the worst possible time and the one everybody chooses.',
          '<strong>Small over large.</strong> A single-collection house museum will nearly always beat the national gallery for an actual afternoon.',
          '<strong>Leave while you are still interested.</strong> This is the whole technique. Stopping early is what makes you want to go back.',
        ] },
        { p: 'Culture is not a quantity to be got through. Ninety minutes, five things, and then a long lunch is not a compromise on a cultural trip. It is the best version of one.' },
      ],
    },

    {
      slug: 'the-eight-seat-counter',
      cat: 'Gastronomy',
      title: 'The eight-seat counter',
      metaTitle: 'The Eight-Seat Counter — Sojourn Journal',
      metaDesc: 'Why the most interesting restaurants keep shrinking, what a counter seat actually buys, and how to get one.',
      excerpt: 'Why the most interesting restaurants keep shrinking — and what a counter seat actually buys.',
      author: 'Camille Ardent',
      date: '2026-03-10',
      dateLabel: '10 March 2026',
      read: '6 min read',
      img: { id: 'photo-1414235077428-338989a2e8c0', alt: 'A plate being set down at a small restaurant table.' },
      tags: ['Gastronomy', 'Restaurants', 'Access'],
      body: [
        { p: 'The most interesting restaurants in the world have been getting smaller for a decade. Not cheaper, not simpler — smaller. Eight seats, ten, sometimes six, one service, one sitting, frequently no menu and increasingly no public booking system at all.' },
        { p: 'It is easy to read this as artificial scarcity. Sometimes it is. Mostly it is a chef solving a real problem.' },
        { h2: 'What the counter is actually for' },
        { p: 'At eight seats, one person can cook and plate every dish at the moment it is ready and hand it directly to the person eating it. Nothing waits under a pass, nothing crosses a dining room, and nothing is compromised to be reproducible forty times a night. The food is simply better, and it is better for structural reasons rather than aspirational ones.' },
        { quote: 'Eight seats is not exclusivity. It is the largest number of people one person can cook for properly.' },
        { p: 'The second thing it buys is information. The chef can see you eat. Courses get adjusted mid-service based on how the room is doing — lighter, slower, an extra one because the table is enjoying itself. That responsiveness disappears completely at forty covers.' },
        { h2: 'The awkward part' },
        { p: 'Small rooms are intimate, which is wonderful with the right company and genuinely difficult with the wrong. You will hear the next conversation. You cannot leave early without it being noticed. If you want a private evening, a counter is the wrong choice, and the honest advice is a larger room with better spacing.' },
        { h2: 'How they are actually booked' },
        { ul: [
          '<strong>Through the property, weeks ahead.</strong> A good hotel in the city holds relationships that no platform has. This is most of what a concierge is now for.',
          '<strong>By being flexible on the night.</strong> Two people on a Tuesday get in where four on a Saturday never will.',
          '<strong>By turning up at opening.</strong> Many keep two seats back and give them to whoever is standing there at six.',
          '<strong>By eating early.</strong> The first sitting is frequently the better one — the kitchen is fresh and the pacing is not compressed.',
        ] },
        { p: 'None of this requires influence. It requires planning three weeks earlier than feels necessary, which is, as usual, the entire secret.' },
      ],
    },

    {
      slug: 'breakfast-is-the-honest-meal',
      cat: 'Gastronomy',
      title: 'Breakfast is the honest meal',
      metaTitle: 'Breakfast Is the Honest Meal — Sojourn Journal',
      metaDesc: 'Dinner is where a hotel performs. Breakfast is where it tells the truth — and most of them fail it badly.',
      excerpt: 'Dinner is where a hotel performs. Breakfast is where it tells you the truth.',
      author: 'Noor Haddad',
      date: '2026-02-24',
      dateLabel: '24 February 2026',
      read: '5 min read',
      img: { id: 'photo-1555396273-367ea4eb4db5', alt: 'A high-ceilinged café with wooden tables and morning light.' },
      tags: ['Gastronomy', 'Hotels', 'Restraint'],
      body: [
        { p: 'Dinner is a performance. The lighting is arranged, the kitchen is at full strength, and the whole apparatus is pointed at making one evening memorable. It is not a reliable guide to anything.' },
        { p: 'Breakfast is where a hotel tells the truth, because nobody is trying. It is served at the least glamorous hour by the smallest team to guests who have not yet put their faces on, and every economy the property has made is visible on the plate.' },
        { h2: 'The buffet problem' },
        { p: 'A vast buffet reads as generosity and functions as the opposite. It is the cheapest way to feed a full house, it guarantees that nothing has been cooked for you, and it converts the quietest hour of the day into a queue. The eggs have been warm for forty minutes. Everyone knows this and the format survives anyway.' },
        { quote: 'A short breakfast menu cooked to order costs the property more and the guest less. Almost nobody does it.' },
        { p: 'The properties worth returning to have generally abandoned it: a page with six things on it, all made when asked, plus bread, fruit and something local that you did not choose. It is faster, it is quieter, and it is the single clearest signal that the kitchen is run by someone who eats there.' },
        { h2: 'What to look for' },
        { ul: [
          '<strong>Is the bread from here?</strong> The most reliable single indicator in hospitality. Good local bread means relationships with the town; industrial rolls mean a delivery contract.',
          '<strong>Is there one thing you would not get at home?</strong> A regional cheese, a preserved fruit, a dish the region actually eats in the morning. Its presence means somebody chose it.',
          '<strong>Can you have it late?</strong> A kitchen that stops at half past nine is running to a schedule that is not yours.',
          '<strong>Is the coffee made by a person?</strong> Not a machine in the corner. This one is nearly infallible.',
        ] },
        { h2: 'And the room service version' },
        { p: 'Frequently the best option, and rarely the one taken. Breakfast on a terrace, at your own hour, in whatever you slept in, is one of the genuine pleasures of staying somewhere good — and on a slow itinerary there is no reason at all to be downstairs at eight.' },
        { p: 'Judge a place by its breakfast. It is the meal it cannot dress up.' },
      ],
    },
  ],
};
