// Content for the nine Sojourn destination pages.
//
// Every `img` id below was downloaded and visually checked before being placed —
// an Unsplash id returning HTTP 200 is no guarantee it shows the right subject.
// If you add one, look at it first and write the alt text from what you saw.

const U = (id, w) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

module.exports = {
  U,
  site: 'https://hhabibhashmi5-source.github.io/sojourn',
  destinations: [
    {
      slug: 'maldives',
      region: 'Islands',
      name: 'Maldives',
      overline: 'Indian Ocean · Private Islands',
      title: 'The Maldives, quietly',
      loc: '26 atolls · 1,192 coral islands · your own, for a while',
      metaTitle: 'Maldives — Sojourn Destinations',
      metaDesc: 'The Maldives, quietly: whole-island buyouts, overwater residences and butler-served days where the only schedule is the tide.',
      hero: { id: 'photo-1507525428034-b723cf961d3e', alt: 'Sunrise over an empty tropical shore.' },
      lead: 'Nowhere else lets you disappear so completely. Here, luxury is not the marble of the suite but the absence of everyone else.',
      body: [
        'We work almost exclusively with whole-island estates and the handful of resorts that hold back villas for private clients. Your days are shaped by tide charts, not itineraries: a reef swum before breakfast, a sandbank set for two at dusk, a dinner the chef composes around whatever the dhoni brought in.',
        'Because seclusion is the point, we plan the seams carefully — the seaplane transfer, the pre-cleared arrival, the butler briefed on your quiet preferences before you land. You should never feel the machinery. You should only feel that you have, at last, gone somewhere.',
      ],
      facts: [
        ['Best season', 'Nov – Apr (dry)'],
        ['Fly to', 'Malé (MLE)'],
        ['Transfer', 'Seaplane / yacht'],
        ['Ideal stay', '7 – 10 nights'],
        ['Good for', 'Wellness · Honeymoon · Family'],
        ['From', '$4,200 / night'],
      ],
      highlights: [
        ['A house on the water', 'Overwater residences with private pools, direct lagoon steps and a butler who stays unseen until wanted.'],
        ['Reefs kept for you', 'Guided drifts with a marine biologist, night snorkels, and house reefs you’ll often have entirely to yourself.'],
        ['Wellness at sea level', 'Overwater spas, resident practitioners and slow, unstructured days engineered for genuine rest.'],
      ],
      gallery: [
        { id: 'photo-1573843981267-be1999ff37cd', alt: 'Overwater villas above a turquoise lagoon.' },
        { id: 'photo-1505228395891-9a51e7e86bf6', alt: 'Surf meeting white sand, seen from above.' },
        { id: 'photo-1516815231560-8f41ec531527', alt: 'A shaded pavilion at the end of a sandbar.' },
        { id: 'photo-1566073771259-6a8506099945', alt: 'Loungers on a timber deck above the water.' },
        { id: 'photo-1544551763-46a013bb70d5', alt: 'A diver over the house reef.' },
        { id: 'photo-1533903345306-15d1c30952de', alt: 'The Milky Way above a palm-lined shore.' },
      ],
      stays: [
        ['The Overwater Residence', 'Two bedrooms suspended over the lagoon, infinity pool, private chef on request.', 'from <b>$6,400</b> / night', { id: 'photo-1571896349842-33c89424de2d', alt: 'The Overwater Residence at dusk.' }],
        ['The Beach House', 'Sand-footed living, a walled garden pool and steps straight to the house reef.', 'from <b>$4,200</b> / night', { id: 'photo-1610641818989-c2051b5e2cfd', alt: 'The Beach House pool at dawn.' }],
        ['The Whole-Island Estate', 'Your own island — nine villas, full staff, a dive team and a yacht on standby.', 'price <b>on request</b>', { id: 'photo-1518509562904-e7ef99cdcc86', alt: 'The whole-island estate, seen from the air.' }],
      ],
      map: 'A custom atlas of atolls, reefs and residences arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Maldives',
    },

    {
      slug: 'swiss-alps',
      region: 'Mountains',
      name: 'Swiss Alps',
      overline: 'Switzerland · Alpine Wellness',
      title: 'Alpine restoration',
      loc: 'Four valleys · thin air · a silence you can hear',
      metaTitle: 'Swiss Alps — Sojourn Destinations',
      metaDesc: 'The Swiss Alps, quietly: low-density chalets, clinical wellness at altitude and valleys kept deliberately empty.',
      hero: { id: 'photo-1527668752968-14dc70a27c95', alt: 'Snow-dusted peaks above a green valley and lake.' },
      lead: 'The mountains do the work. Our task is simply to remove everything between you and them.',
      body: [
        'We favour the quieter valleys over the famous ones — places where the lift queue is a rumour and the chalet next door is a kilometre away. In winter that means private guides and untracked snow before the day begins; in summer, wildflower meadows, cold lakes and a cable car you may well have to yourself.',
        'Switzerland is also where clinical wellness is taken seriously. Where it suits, we build the week around a genuine programme — diagnostics, altitude training, sleep work — and then leave long afternoons entirely unplanned, which is usually the part that does the healing.',
      ],
      facts: [
        ['Best season', 'Dec – Mar · Jun – Sep'],
        ['Fly to', 'Zurich (ZRH) / Geneva (GVA)'],
        ['Transfer', 'Private rail / helicopter'],
        ['Ideal stay', '5 – 8 nights'],
        ['Good for', 'Wellness · Family · Winter sport'],
        ['From', '$3,800 / night'],
      ],
      highlights: [
        ['Chalets held back', 'A short list of private chalets with staff, spa and ski-room — booked directly, never through a portal.'],
        ['Medicine, not massage', 'Access to Switzerland’s clinical wellness houses, with programmes built around real diagnostics.'],
        ['Empty mountains', 'First tracks with a private guide, closed-piste mornings and huts opened out of season for lunch.'],
      ],
      gallery: [
        { id: 'photo-1506905925346-21bda4d32df4', alt: 'Snow peaks rising above a sea of cloud at sunrise.' },
        { id: 'photo-1476514525535-07fb3b4ae5f1', alt: 'A wooden boat on a still alpine lake.' },
        { id: 'photo-1508739773434-c26b3d09e071', alt: 'First light on a jagged mountain ridge.' },
        { id: 'photo-1502786129293-79981df4e689', alt: 'A turquoise glacial lake ringed by pines.' },
        { id: 'photo-1519681393784-d120267933ba', alt: 'The night sky above snow-covered peaks.' },
        { id: 'photo-1486870591958-9b9d0d1dda99', alt: 'Late sun on a mountain face above golden grass.' },
      ],
      stays: [
        ['The Terrace Suite', 'An open-air bed on a private deck, glass-walled bath, and the valley for a view.', 'from <b>$3,800</b> / night', { id: 'photo-1596394516093-501ba68a0ba6', alt: 'An open-air bed on a terrace above the valley.' }],
        ['The Grand Chalet', 'Six bedrooms, resident chef, ski-room and a spa cut into the hillside.', 'from <b>$9,500</b> / night', { id: 'photo-1590490360182-c33d57733427', alt: 'A panelled suite with deep drapes and a fire.' }],
        ['The Clinic Residence', 'A private wing at a wellness house — programme, practitioners and total discretion.', 'price <b>on request</b>', { id: 'photo-1578683010236-d716f9a3f461', alt: 'A calm bedroom opening to a mountain view.' }],
      ],
      map: 'A valley-by-valley atlas of chalets, huts and lifts arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Alps',
    },

    {
      slug: 'amalfi-coast',
      region: 'Coast',
      name: 'Amalfi Coast',
      overline: 'Southern Italy · Cliffside Villas',
      title: 'A coast, privately held',
      loc: 'Fifty kilometres of cliff · lemon terraces · one road',
      metaTitle: 'Amalfi Coast — Sojourn Destinations',
      metaDesc: 'The Amalfi Coast, quietly: staffed cliffside villas, lemon-grove terraces and a private boat to keep you off the one road.',
      hero: { id: 'photo-1612698093158-e07ac200d44e', alt: 'Pastel houses stacked on the cliffs above a turquoise sea.' },
      lead: 'The coast is not a secret. Having it to yourself, however, remains entirely arrangeable.',
      body: [
        'The trick here is the water. With a boat and a skipper on call, the coast rearranges itself: you leave before the coaches arrive, swim off Li Galli at ten, eat somewhere reachable only by tender, and come home along a cliff face turning gold. The famous road becomes something other people sit in.',
        'On land we place you in staffed villas above the towns rather than in them — lemon terraces, a cook who shops the morning market, and enough height that the noise stays where it belongs. Naples and Pompeii sit close enough for a half day, if you want one.',
      ],
      facts: [
        ['Best season', 'May – Jun · Sep – Oct'],
        ['Fly to', 'Naples (NAP)'],
        ['Transfer', 'Private car / boat'],
        ['Ideal stay', '6 – 9 nights'],
        ['Good for', 'Couples · Food · Family'],
        ['From', '$2,900 / night'],
      ],
      highlights: [
        ['A boat on call', 'A skipper and tender for the length of your stay — the only sane way to move along this coast.'],
        ['Villas above the towns', 'Staffed houses with lemon terraces, sea pools and the crowds a comfortable distance below.'],
        ['Tables held', 'Kitchens that stopped taking bookings years ago, and a cook who shops the market for the nights you stay in.'],
      ],
      gallery: [
        { id: 'photo-1516483638261-f4dbaf036963', alt: 'A cliffside village of coloured houses on the Italian coast.' },
        { id: 'photo-1534445867742-43195f401b6c', alt: 'A harbour village seen from the coastal path above.' },
        { id: 'photo-1499678329028-101435549a4e', alt: 'A coastal village at sunset, lights coming on.' },
        { id: 'photo-1523365154888-8a758819b722', alt: 'A watchtower above sea stacks on a Mediterranean shore.' },
        { id: 'photo-1467003909585-2f8a72700288', alt: 'A plated course at a small coastal kitchen.' },
        { id: 'photo-1471193945509-9ad0617afabf', alt: 'Produce stacked at a morning market.' },
      ],
      stays: [
        ['Villa Sopra', 'Four bedrooms above the lemon terraces, sea pool, cook and housekeeper in residence.', 'from <b>$4,600</b> / night', { id: 'photo-1590490360182-c33d57733427', alt: 'A panelled bedroom with tall shuttered windows.' }],
        ['The Cliff Apartment', 'A two-bedroom eyrie cut into the rock, with a lift down to a private swimming platform.', 'from <b>$2,900</b> / night', { id: 'photo-1600210492486-724fe5c67fb0', alt: 'A bright living room with deep sofas and tall windows.' }],
        ['The Estate at Ravello', 'A whole garden estate above the coast — eight bedrooms, full staff, boat included.', 'price <b>on request</b>', { id: 'photo-1618773928121-c32242e63f39', alt: 'A quiet, warm-toned bedroom.' }],
      ],
      map: 'A boat-by-boat atlas of coves, tables and swimming platforms arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Amalfi Coast',
    },

    {
      slug: 'kyoto',
      region: 'Culture',
      name: 'Kyoto',
      overline: 'Japan · Cultural Immersion',
      title: 'Ritual and quiet',
      loc: 'Seventeen world heritage sites · one very early alarm',
      metaTitle: 'Kyoto — Sojourn Destinations',
      metaDesc: 'Kyoto, quietly: private ryokan stays, tea masters, temple mornings before the gates open and craftsmen who rarely take visitors.',
      hero: { id: 'photo-1493976040374-85c8e12f0c0e', alt: 'A pagoda at the end of a quiet Kyoto lane at first light.' },
      lead: 'Kyoto rewards the early and the introduced. We handle both.',
      body: [
        'The difference between Kyoto as a queue and Kyoto as a revelation is about ninety minutes of sleep. We build mornings that start before the gates open — a moss garden alone, a temple hall unlocked for you, a priest with twenty minutes and no audience — and then let the afternoons go soft.',
        'The other half is access. Tea masters, indigo dyers, a knife-maker in the fifth generation, a kaiseki counter with eight seats: these are relationships, not bookings. Our fixer in Kyoto has spent fifteen years building them, and they are the reason the week feels like a private education rather than a tour.',
      ],
      facts: [
        ['Best season', 'Mar – May · Oct – Nov'],
        ['Fly to', 'Osaka (KIX)'],
        ['Transfer', 'Private car / shinkansen'],
        ['Ideal stay', '5 – 7 nights'],
        ['Good for', 'Culture · Food · Couples'],
        ['From', '$1,900 / night'],
      ],
      highlights: [
        ['Temples before the gates', 'Private early access to halls and gardens normally met three deep in visitors.'],
        ['Masters, not demonstrations', 'Time with tea practitioners, dyers and craftsmen who do not otherwise take guests.'],
        ['Eight seats', 'Counters and kaiseki rooms held for our members, including a few that take no public bookings.'],
      ],
      gallery: [
        { id: 'photo-1478436127897-769e1b3f0f36', alt: 'Vermilion torii gates along an empty path.' },
        { id: 'photo-1545569341-9eb8b30979d9', alt: 'A pagoda above the city at dusk.' },
        { id: 'photo-1492571350019-22de08371fd3', alt: 'A torii gate standing in still lake water.' },
        { id: 'photo-1524413840807-0c3cb6fa808d', alt: 'Cherry blossom lit above a narrow canal.' },
        { id: 'photo-1445264718234-a623be589d37', alt: 'Light falling through a tall green grove.' },
        { id: 'photo-1480796927426-f609979314bd', alt: 'A traditional shopfront on a quiet street.' },
      ],
      stays: [
        ['The Machiya', 'A restored townhouse for two — cedar bath, private garden, housekeeper each morning.', 'from <b>$1,900</b> / night', { id: 'photo-1611892440504-42a792e24d32', alt: 'A dark-timber bedroom opening onto a small garden.' }],
        ['The Ryokan Suite', 'Two tatami rooms, private onsen, and kaiseki served in your own dining room.', 'from <b>$3,100</b> / night', { id: 'photo-1582719478250-c89cae4dc85b', alt: 'A warm wooden room with garden doors open.' }],
        ['The Temple Residence', 'A sub-temple wing kept for guests, with the grounds to yourself after closing.', 'price <b>on request</b>', { id: 'photo-1618773928121-c32242e63f39', alt: 'A restrained, low-lit bedroom.' }],
      ],
      map: 'A ward-by-ward atlas of temples, counters and ateliers arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Kyoto',
    },

    {
      slug: 'cyclades',
      region: 'Coast',
      name: 'Cyclades',
      overline: 'Greece · The Aegean',
      title: 'The Aegean, unhurried',
      loc: 'Two hundred and twenty islands · twenty-four inhabited',
      metaTitle: 'Cyclades — Sojourn Destinations',
      metaDesc: 'The Cyclades, quietly: cave houses above the caldera, a private caïque between the smaller islands, and tavernas the ferries never reach.',
      hero: { id: 'photo-1570077188670-e3a8d69ac5ff', alt: 'A whitewashed Cycladic village above the Aegean at dusk.' },
      lead: 'The islands everyone knows are ninety minutes from the islands nobody does. That is the whole plan.',
      body: [
        'We base you somewhere beautiful and well-served — a cave house on the caldera, a stone villa above a bay — and then spend the days elsewhere. With a caïque and a skipper you can be at an empty cove by ten, at a taverna with six tables by two, and back for the light without ever queueing for a ferry.',
        'Late spring and September are the honest answer on timing: the sea is warm, the meltemi is manageable, and the islands are still working islands rather than a set. We build in a slow start most days, because the Aegean is not somewhere to be efficient.',
      ],
      facts: [
        ['Best season', 'May – Jun · Sep – Oct'],
        ['Fly to', 'Athens (ATH) / Santorini (JTR)'],
        ['Transfer', 'Private caïque / helicopter'],
        ['Ideal stay', '7 – 10 nights'],
        ['Good for', 'Couples · Sailing · Food'],
        ['From', '$2,400 / night'],
      ],
      highlights: [
        ['A caïque and a skipper', 'A traditional wooden boat on call — the difference between three islands and thirteen.'],
        ['Houses in the rock', 'Cave houses and stone villas with private terraces above the caldera, staffed on request.'],
        ['Tables the ferries miss', 'Six-table tavernas on islands without a port, reachable only the way we arrive.'],
      ],
      gallery: [
        { id: 'photo-1613395877344-13d4a8e0d49e', alt: 'Blue domes above the caldera in morning light.' },
        { id: 'photo-1601581875309-fafbf2d3ed3a', alt: 'Tables set at the water’s edge in a Cycladic town.' },
        { id: 'photo-1560703650-ef3e0f254ae0', alt: 'Whitewashed terraces above a deep blue sea.' },
        { id: 'photo-1533105079780-92b9be482077', alt: 'A narrow island lane opening to the water.' },
        { id: 'photo-1555993539-1732b0258235', alt: 'Classical columns against a clear sky.' },
        { id: 'photo-1467003909585-2f8a72700288', alt: 'A plated course at a small island kitchen.' },
      ],
      stays: [
        ['The Cave House', 'Two vaulted bedrooms cut into the cliff, plunge pool, and the caldera off the terrace.', 'from <b>$2,400</b> / night', { id: 'photo-1600210492486-724fe5c67fb0', alt: 'A bright, pared-back living room.' }],
        ['The Bay Villa', 'A stone house above its own cove, four bedrooms, cook and boat included.', 'from <b>$4,100</b> / night', { id: 'photo-1631049307264-da0ec9d70304', alt: 'A calm bedroom in soft daylight.' }],
        ['The Island Estate', 'A private headland with three houses, full staff and a crewed caïque on standby.', 'price <b>on request</b>', { id: 'photo-1512918728675-ed5a9ecdebfd', alt: 'A light-filled bedroom with a linen-dressed bed.' }],
      ],
      map: 'An island-by-island atlas of coves, tavernas and anchorages arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Cyclades',
    },

    {
      slug: 'provence',
      region: 'Countryside',
      name: 'Provence',
      overline: 'Southern France · Countryside',
      title: 'Slow Provençal days',
      loc: 'Lavender, limestone and a market every morning somewhere',
      metaTitle: 'Provence — Sojourn Destinations',
      metaDesc: 'Provence, quietly: a private mas with a cook, market mornings, cellars off the map and afternoons deliberately left empty.',
      hero: { id: 'photo-1499002238440-d264edd596ec', alt: 'Rows of lavender across the countryside at sunset.' },
      lead: 'The point of Provence is that nothing much happens, extremely well.',
      body: [
        'A mas with a long table, a pool under plane trees, and a cook who arrives with whatever the market had. That is most of it. We add the parts that are hard to arrange alone: a cellar visit with the winemaker rather than the tasting room, a truffle morning in season, a chef who will come and cook for eight without turning it into an event.',
        'The villages do the rest — Gordes, Ménerbes, Roussillon — best taken one per day and abandoned by noon. July and August are hot and full; we push almost everyone to late May, June or September, when the lavender is right and the terraces are yours.',
      ],
      facts: [
        ['Best season', 'May – Jun · Sep'],
        ['Fly to', 'Marseille (MRS) / Nice (NCE)'],
        ['Transfer', 'Private car'],
        ['Ideal stay', '7 – 10 nights'],
        ['Good for', 'Family · Food & wine · Couples'],
        ['From', '$2,100 / night'],
      ],
      highlights: [
        ['A mas of your own', 'Private farmhouses with pools, gardens and staff who make themselves scarce by ten.'],
        ['Cellars off the list', 'Winemakers in Châteauneuf and the Luberon who pour for us and not for the public.'],
        ['Markets, then nothing', 'A different market each morning, and afternoons we deliberately leave empty.'],
      ],
      gallery: [
        { id: 'photo-1471193945509-9ad0617afabf', alt: 'Bundled produce at a village market stall.' },
        { id: 'photo-1464226184884-fa280b87c399', alt: 'Vegetables laid out at a morning market.' },
        { id: 'photo-1471623320832-752e8bbf8413', alt: 'A bicycle against iron railings on a quiet street.' },
        { id: 'photo-1441974231531-c6227db76b6e', alt: 'A path through an old forest in low sun.' },
        { id: 'photo-1467003909585-2f8a72700288', alt: 'A plated course at a country table.' },
        { id: 'photo-1533055640609-24b498dfd74c', alt: 'Hats stacked on a market stall.' },
      ],
      stays: [
        ['Le Mas', 'Five bedrooms around a courtyard, pool under the planes, cook three days a week.', 'from <b>$2,100</b> / night', { id: 'photo-1512918728675-ed5a9ecdebfd', alt: 'A white bedroom with light through tall shutters.' }],
        ['The Vineyard House', 'A working domaine with guest wing, cellar access and dinner among the vines.', 'from <b>$3,300</b> / night', { id: 'photo-1600210492486-724fe5c67fb0', alt: 'A relaxed living room in warm neutral tones.' }],
        ['The Village Château', 'A small château above a hill village — ten bedrooms, full staff, chef on request.', 'price <b>on request</b>', { id: 'photo-1590490360182-c33d57733427', alt: 'A formal bedroom with heavy drapes.' }],
      ],
      map: 'A village-by-village atlas of markets, cellars and tables arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Provence',
    },

    {
      slug: 'bali',
      region: 'Islands',
      name: 'Bali',
      overline: 'Indonesia · Jungle & Ceremony',
      title: 'Jungle and ceremony',
      loc: 'Twenty thousand temples · two coasts · one very old calendar',
      metaTitle: 'Bali — Sojourn Destinations',
      metaDesc: 'Bali, quietly: cliff villas above Uluwatu, healers and ceremony in the Ubud hills, and the island’s crowds carefully avoided.',
      hero: { id: 'photo-1573790387438-4da905039392', alt: 'Palms on a cliffside beach in Bali.' },
      lead: 'Bali is two islands: the one on the postcards, and the one that is still, unmistakably, a religion with a coastline attached.',
      body: [
        'We split most weeks between the cliffs and the hills. Uluwatu for the water — a villa on the edge, a break below, sunsets that empty the terrace of conversation. Then inland to Ubud and beyond, where the temperature drops, the rice terraces start, and the days take their shape from the ceremonial calendar rather than yours.',
        'Ceremony is the part people underestimate. With the right introduction you are not watching a performance but sitting at the edge of something real — a temple anniversary, a blessing at dawn, a healer who will see you because our fixer’s family has known his for thirty years. We ask that you go gently with it.',
      ],
      facts: [
        ['Best season', 'Apr – Jun · Sep – Oct'],
        ['Fly to', 'Denpasar (DPS)'],
        ['Transfer', 'Private car / helicopter'],
        ['Ideal stay', '8 – 12 nights'],
        ['Good for', 'Couples · Wellness · Surf'],
        ['From', '$1,600 / night'],
      ],
      highlights: [
        ['Cliffs and a break below', 'Villas on the Bukit edge with pools that end in air and a surf guide who reads the tide.'],
        ['The hills after', 'Rice terraces, river gorges and a cooler second week in and beyond Ubud.'],
        ['Ceremony, properly introduced', 'Temple days and healers reached through relationships rather than tickets.'],
      ],
      gallery: [
        { id: 'photo-1555400038-63f5ba517a47', alt: 'Terraced rice fields stepping down a green valley.' },
        { id: 'photo-1518548419970-58e3b4079ab2', alt: 'A sea temple on a rock at sunset.' },
        { id: 'photo-1604999333679-b86d54738315', alt: 'A lakeside temple reflected in still water.' },
        { id: 'photo-1531778272849-d1dd22444c06', alt: 'A split temple gate framing a volcano at dawn.' },
        { id: 'photo-1537953773345-d172ccf13cf1', alt: 'A stone gateway mirrored in still water.' },
        { id: 'photo-1540541338287-41700207dee6', alt: 'A clifftop pool above the ocean.' },
      ],
      stays: [
        ['The Cliff Villa', 'Three bedrooms on the Bukit edge, infinity pool, staff and a surf guide on call.', 'from <b>$1,600</b> / night', { id: 'photo-1611892440504-42a792e24d32', alt: 'A dark-timber bedroom open to a courtyard.' }],
        ['The River House', 'A jungle house above a gorge — outdoor bath, private chef, silence after dark.', 'from <b>$2,300</b> / night', { id: 'photo-1520250497591-112f2f40a3f4', alt: 'A pool set among palms below green ridges.' }],
        ['The Ubud Compound', 'A walled family compound with five pavilions, full staff and a resident healer.', 'price <b>on request</b>', { id: 'photo-1582719478250-c89cae4dc85b', alt: 'A warm wooden room opening to the garden.' }],
      ],
      map: 'A coast-and-hills atlas of villas, temples and breaks arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Bali',
    },

    {
      slug: 'norway',
      region: 'Mountains',
      name: 'Norway',
      overline: 'Norway · Fjords & Northern Light',
      title: 'Fjords in silence',
      loc: 'A thousand fjords · a coastline longer than the equator',
      metaTitle: 'Norway — Sojourn Destinations',
      metaDesc: 'Norway, quietly: design lodges above the fjords, a private vessel, and the long northern light — or the dark, and what moves in it.',
      hero: { id: 'photo-1601439678777-b2b3c56fa627', alt: 'A fjord seen from the cliffs above.' },
      lead: 'Scale is the luxury here. Everything else — the lodge, the boat, the food — is in service of getting you somewhere large and leaving you there.',
      body: [
        'In summer the light simply does not go, and the days lose their edges: a fjord swum at eleven at night, a hike that starts after dinner, a vessel that moves you between anchorages while you sleep. We favour small design lodges and a chartered boat over hotels, because the point is to be in the landscape rather than looking at it through glass.',
        'The winter case is different and, for some, better. Above the Arctic circle from late September the aurora becomes a reasonable expectation rather than a gamble, and the cold makes everything — the sauna, the sea, the quiet — considerably more vivid.',
      ],
      facts: [
        ['Best season', 'Jun – Aug · Oct – Mar (aurora)'],
        ['Fly to', 'Bergen (BGO) / Tromsø (TOS)'],
        ['Transfer', 'Private vessel / seaplane'],
        ['Ideal stay', '6 – 9 nights'],
        ['Good for', 'Couples · Photography · Solitude'],
        ['From', '$2,700 / night'],
      ],
      highlights: [
        ['A vessel, not a hotel', 'A crewed boat that moves between anchorages overnight, so mornings start somewhere new and empty.'],
        ['Architecture in the landscape', 'A handful of small design lodges built to disappear into the rock they sit on.'],
        ['The light, either kind', 'Midnight sun in summer; from late September, aurora nights above the Arctic circle.'],
      ],
      gallery: [
        { id: 'photo-1531366936337-7c912a4589a7', alt: 'The aurora over a snow-covered valley.' },
        { id: 'photo-1520769669658-f07657f5a307', alt: 'A Norwegian flag against a low northern sun.' },
        { id: 'photo-1470071459604-3b5ec3a7fe05', alt: 'Cloud moving across steep green cliffs.' },
        { id: 'photo-1444927714506-8492d94b4e3d', alt: 'Blue mountain ridges fading into mist.' },
        { id: 'photo-1552083375-1447ce886485', alt: 'A deep lake enclosed by forested slopes.' },
        { id: 'photo-1600298881974-6be191ceeda1', alt: 'A snow-streaked peak above dark pines.' },
      ],
      stays: [
        ['The Fjord Cabin', 'Two bedrooms, floor-to-ceiling glass, wood-fired sauna and steps into cold water.', 'from <b>$2,700</b> / night', { id: 'photo-1578683010236-d716f9a3f461', alt: 'A calm bedroom facing a wide landscape view.' }],
        ['The Terrace Lodge', 'An open-sided room above the water, for the aurora or the midnight sun.', 'from <b>$3,900</b> / night', { id: 'photo-1596394516093-501ba68a0ba6', alt: 'An open-air bed on a deck above a valley.' }],
        ['The Chartered Vessel', 'A crewed boat for up to eight — cabins, a chef, and a new anchorage each morning.', 'price <b>on request</b>', { id: 'photo-1631049307264-da0ec9d70304', alt: 'A compact, well-made cabin bedroom.' }],
      ],
      map: 'A fjord-by-fjord atlas of anchorages, lodges and trailheads arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Norway',
    },

    {
      slug: 'marrakech',
      region: 'Culture',
      name: 'Marrakech',
      overline: 'Morocco · Riads & the High Atlas',
      title: 'Riads and rose light',
      loc: 'A walled medina · a mountain range an hour away',
      metaTitle: 'Marrakech — Sojourn Destinations',
      metaDesc: 'Marrakech, quietly: a private riad behind a blank door, artisan ateliers, and the High Atlas an hour from the medina wall.',
      hero: { id: 'photo-1539020140153-e479b8c22e70', alt: 'Carved zellige tilework around a Moroccan fountain.' },
      lead: 'Everything worth seeing here is behind a plain door, and the doors open for people who are introduced.',
      body: [
        'A riad is a house turned inward: blank wall to the street, and a courtyard of citrus and tilework once you are through. We take whole riads rather than rooms — five or six bedrooms, a cook, a rooftop for breakfast, and staff who understand that guests come here to be left alone.',
        'The medina is best walked early and with someone who knows which workshops are real. Afternoons we tend to send people out — the Agafay desert for dusk, or up into the High Atlas, an hour away and fifteen degrees cooler, where the valleys still work the way they always have.',
      ],
      facts: [
        ['Best season', 'Mar – May · Oct – Nov'],
        ['Fly to', 'Marrakech (RAK)'],
        ['Transfer', 'Private car'],
        ['Ideal stay', '4 – 7 nights'],
        ['Good for', 'Couples · Design · Short breaks'],
        ['From', '$1,400 / night'],
      ],
      highlights: [
        ['A riad, whole', 'Entire houses with courtyard, roof terrace, cook and staff — never a room in someone else’s.'],
        ['Ateliers, not stalls', 'Metalworkers, zellige cutters and weavers who supply the houses you already know.'],
        ['The Atlas by lunch', 'Berber valleys an hour from the wall, and a table somewhere with a view and no menu.'],
      ],
      gallery: [
        { id: 'photo-1489749798305-4fea3ae63d43', alt: 'An earthen town among palms below dry mountains.' },
        { id: 'photo-1445019980597-93fa8acb246c', alt: 'A rooftop terrace looking toward the mountains.' },
        { id: 'photo-1551882547-ff40c63fe5fa', alt: 'A courtyard pool among palms at dusk.' },
        { id: 'photo-1533055640609-24b498dfd74c', alt: 'Hats stacked on a souk stall.' },
        { id: 'photo-1464226184884-fa280b87c399', alt: 'Produce laid out at a morning market.' },
        { id: 'photo-1518998053901-5348d3961a04', alt: 'A pared-back gallery hung with photographs.' },
      ],
      stays: [
        ['The Riad', 'Six bedrooms around a citrus courtyard, plunge pool, cook and roof terrace for breakfast.', 'from <b>$1,400</b> / night', { id: 'photo-1445019980597-93fa8acb246c', alt: 'A rooftop set for breakfast above the town.' }],
        ['The Palmeraie Villa', 'A garden house outside the walls — five bedrooms, pool, staff and total quiet.', 'from <b>$2,200</b> / night', { id: 'photo-1560448204-e02f11c3d0e2', alt: 'A soft-toned sitting room with deep armchairs.' }],
        ['The Atlas Kasbah', 'A restored kasbah in a Berber valley, taken whole, an hour from the medina.', 'price <b>on request</b>', { id: 'photo-1618773928121-c32242e63f39', alt: 'A warm, low-lit bedroom.' }],
      ],
      map: 'A door-by-door atlas of riads, ateliers and Atlas valleys arrives in a later phase. For now, your advisor plots it by hand.',
      ctaTitle: 'Plan your Marrakech',
    },
  ],
};
